# Generated by Django 4.0.5 on 2022-07-19 10:17

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='Employee',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=250)),
                ('salary', models.FloatField()),
                ('linkedin', models.URLField()),
                ('department', models.CharField(max_length=350)),
                ('employee_num', models.CharField(blank=True, max_length=6, null=True)),
                ('date_joined', models.DateTimeField(auto_now_add=True)),
                ('supervisor', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='sub_ordinates', to=settings.AUTH_USER_MODEL)),
            ],
        ),
    ]
